version: '3.7'

services:
        web:
                build: .
                command: python /code/manage.py runserver 0.0.0.0:8000
                environment:
                        - SECRET_KEY=fc4lv*(d)k6g%q&ai@=cpx7^yj55ijp)&pt!n)8*g30pun@uao
                        - DEBUG=1
                volumes:
                        - .:/code
                ports:
                        - 8000:8000
                depends_on:
                        - db

        db:
                image: postgres:11
                volumes:
                        - postgres_data:/var/lib/postgresql/data/
                environment:
                        - "POSTGRES_HOST_AUTH_METHOD=trust"


volumes:
        postgres_data:
