# Generated by Django 3.0.1 on 2021-01-04 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='details',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
